export enum ContextType {
    ENCAPSULATION_START,
    ENCAPSULATION_END,
    ARRAY_START,
    ARRAY_END,
    SCOPE_START,
    SCOPE_END,
    LINE_END,
    ARROW,
    SEPARATOR,
    DIVIDER,
    ELLIPSIS
}