name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  OS: ubuntu-latest
  NODE_VERSION: 18
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  PAGES_PATH: ./pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build the project in node v${{ env.NODE_VERSION }}}

    runs-on: ${{ env.OS }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js v${{ env.NODE_VERSION }}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}}
        cache: npm
    - run: npm ci
    - run: npm run build

  test:
    name: Test the project in v${{ env.NODE_VERSION }}}

    runs-on: ${{ env.OS }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js v${{ env.NODE_VERSION }}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}}
        cache: npm
    - run: npm ci
    - run: npm test
    - name: Uploading test page artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '${{ env.PAGES_PATH }}}/test-results/index.html'
        retention-days: 1

  pages:
    name: Deploy the test results to GitHub Pages

    needs:
    - test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ${{ env.OS }}

    steps:
    - uses: actions/checkout@v3
    - name: Download all page artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ env.PAGES_PATH }}}/${{ env.BRANCH_NAME }}}
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ env.PAGES_PATH }}}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
