name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build the project in node v18

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm ci
    - run: npm run build

  test:
    name: Test the project in v18

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm ci
    - run: npm test
    - name: Cache pages
      uses: actions/cache@v3.3.0
      with:
        path: './pages'
        key: page-cache

  pages:
    name: Deploy the test results to GitHub Pages

    needs:
    - test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore pages
      uses: actions/cache@v3.3.0
      with:
        path: './pages'
        key: page-cache
        fail-on-cache-miss: true
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './pages'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
