name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
  pull_request_target:
    types: 
      - closed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build the project in node

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Download all dependencies
        run: npm ci
      - name: Build the project
        run: npm run build

  test:
    name: Test the project

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Download all dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Uploading the test page artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: './pages/test-results/index.html'
          retention-days: 1
          
  wiki:
    name: Upload wiki pages
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    # Consider the wiki invalid if either of these aren't functional
    needs:
      - test
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Download all dependencies
        run: npm ci
      - name: Build the wiki pages
        run: npm run wiki
      - name: Uploading the wiki artifact
        uses: actions/upload-artifact@v3
        with:
          name: wiki
          path: './pages/**'
          retention-days: 1

  pages:
    name: Deploy the artifacts to GitHub Pages
    if: always() && (github.event_name != 'pull_request' || github.event.pull_request.merged == true)

    needs:
      - test
      - wiki

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download all page artifacts
        uses: actions/download-artifact@v3
        with:
          path: './pages'
      - name: Move the wiki to root
        run: mv ./pages/wiki/* ./pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './pages'
      - name: Show all files
        run: ls -R
        working-directory: './pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
