name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    types: 
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build the project in node

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: npm
    - run: npm ci
    - run: npm run build

  test:
    name: Test the project

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: npm
    - run: npm ci
    - run: npm test
    - name: Uploading test page artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: './pages/test-results/index.html'
        retention-days: 1

  pages:
    name: Deploy the test results to GitHub Pages
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.merged == true }}

    needs:
    - test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download all page artifacts
      uses: actions/download-artifact@v3
      with:
        path: './pages'
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './pages'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
